name: Run Colab Notebook

on:
  schedule:
    - cron: '0 * * * *'  # every hour (adjust as needed)
  workflow_dispatch:     # manual run button

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    environment: chat
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install jupyter
     
      - name: Write service account key from GitHub Secret
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" > sa.json

      - name: Run notebook
        env: 
          SERVICE_ACCOUNT_JSON: "sa.json"
        run: |
          jupyter nbconvert --to notebook --execute token_generator.ipynb --output executed.ipynb
